spring.application.name=api-gateway

server.port=8080

# Enable gateway routes refresh
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

#spring.cloud.gateway.globalcors.corsConfigurations.[*].allowedOrigins=http://localhost:3000
#spring.cloud.gateway.globalcors.corsConfigurations.[*].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
#spring.cloud.gateway.globalcors.corsConfigurations.[*].allowedHeaders=*
#spring.cloud.gateway.globalcors.corsConfigurations.[*].allowCredentials=true

# Define routes for services
spring.cloud.gateway.routes[0].id = identity
spring.cloud.gateway.routes[0].uri = http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0] = Path=/api/v1/auth/**

spring.cloud.gateway.routes[1].id = customer
spring.cloud.gateway.routes[1].uri = http://localhost:8081
spring.cloud.gateway.routes[1].predicates[0] = Path=/api/v1/customers/**

spring.cloud.gateway.routes[2].id = diary_entry
spring.cloud.gateway.routes[2].uri = http://localhost:8082
spring.cloud.gateway.routes[2].predicates[0] = Path=/api/v1/diaries/**