spring.application.name=ai-chat
server.port=8083

# MongoDB Configuration
spring.data.mongodb.uri=mongodb+srv://tannm2005:63W9tO6SGORuuUoi@cluster0.6kf03.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=mindary_ver2

# Gemini API Configuration
gemini.api.key=AIzaSyBvyfIftMAJBv4P02QkBXbEd8sAEqh1ACE 